import { ArrowLeft, Bot, Send, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { addTicketMessage, getTicket, updateTicket, type TicketRecord } from './ticket.api';
import { analyzeTicket, type AIAnalysis } from '../ai-assistant/ai.api';
function label(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
export function TicketDetailsPage(){const {ticketId=''}=useParams();const [ticket,setTicket]=useState<TicketRecord|null>(null);const [analysis,setAnalysis]=useState<AIAnalysis|null>(null);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const load=()=>void getTicket(ticketId).then(setTicket).catch(e=>setError(e instanceof Error?e.message:'Unable to load ticket')); useEffect(()=>{load()},[ticketId]);
 if(!ticket)return <div className="sf-page"><div className="sf-page__inner">{error?<div className="sf-alert">{error}</div>:<div className="sf-empty">Loading ticket…</div>}</div></div>;
 const currentTicket = ticket; async function statusChange(status:string){try{setTicket(await updateTicket(currentTicket.id,{status}))}catch(e){setError(e instanceof Error?e.message:'Unable to update ticket')}}
 async function send(){if(!message.trim())return;try{await addTicketMessage(currentTicket.id,message.trim());setMessage('');load()}catch(e){setError(e instanceof Error?e.message:'Unable to send message')}}
 async function runAI(){try{setAnalysis(await analyzeTicket({ticketId:currentTicket.id}))}catch(e){setError(e instanceof Error?e.message:'AI analysis failed')}}
 return <div className="sf-page ticket-detail-page"><div className="sf-page__inner sf-stack"><Link className="sf-back" to="/tickets"><ArrowLeft size={15}/>Back to Tickets</Link>{error&&<div className="sf-alert">{error}</div>}
 <header className="sf-card sf-page-header" style={{padding:'18px 20px'}}><div><div style={{display:'flex',gap:10,alignItems:'center'}}><span className="sf-link">{currentTicket.ticketNumber}</span><span className={`sf-pill sf-status--${currentTicket.status.toLowerCase()}`}>{label(currentTicket.status)}</span><span className={`sf-pill sf-priority--${currentTicket.priority.toLowerCase()}`}>{label(currentTicket.priority)}</span></div><h1 style={{margin:'8px 0 0',fontSize:19,fontWeight:650,color:'#17233f'}}>{currentTicket.subject}</h1><p className="sf-subheading">Created {new Date(currentTicket.createdAt).toLocaleString()} · Updated {new Date(currentTicket.updatedAt).toLocaleString()}</p></div><select className="sf-select" style={{width:145}} value={currentTicket.status} onChange={e=>statusChange(e.target.value)}><option value="OPEN">Open</option><option value="PENDING">Pending</option><option value="RESOLVED">Resolved</option><option value="CLOSED">Closed</option></select></header>
 <div className="sf-detail-grid"><section className="sf-card"><div className="sf-card__header"><div className="sf-section-title">Conversation</div></div><div className="sf-message-thread">{currentTicket.messages.map(m=><div className="sf-thread-item" key={m.id}><div className="sf-avatar">{m.senderType==='AI'?<Bot size={15}/>:<UserRound size={15}/>}</div><div><div className="sf-thread-item__body"><div style={{fontSize:11,fontWeight:700,color:'#667085',marginBottom:5}}>{label(m.senderType)}{m.user?` · ${m.user.name}`:''}</div>{m.content}</div><div className="sf-thread-item__meta">{new Date(m.createdAt).toLocaleString()}</div></div></div>)}</div><div className="sf-chat__composer"><input className="sf-input" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a reply…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}}/><button className="sf-button sf-button--primary" onClick={send}><Send size={15}/>Send</button></div></section>
 <aside className="sf-detail-sidebar"><section className="sf-card sf-sidebar-card"><div className="sf-section-title">Customer</div><div style={{marginTop:12}}><div style={{fontWeight:650}}>{currentTicket.customer.name}</div><div style={{fontSize:12,color:'#667085',marginTop:4}}>{currentTicket.customer.email}</div><div style={{fontSize:12,color:'#667085',marginTop:4}}>{currentTicket.customer.company||'No company'}</div></div></section><section className="sf-card sf-sidebar-card"><div className="sf-section-title">AI analysis</div>{analysis?<div style={{marginTop:12}}><div className="sf-detail-row"><span>Category</span><b>{label(analysis.category)}</b></div><div className="sf-detail-row"><span>Priority</span><b>{label(analysis.priority)}</b></div><div className="sf-detail-row"><span>Sentiment</span><b>{label(analysis.sentiment)}</b></div><div className="sf-detail-row"><span>Confidence</span><b>{Math.round(analysis.confidence*(analysis.confidence<=1?100:1))}%</b></div><p style={{fontSize:12,lineHeight:1.6,color:'#667085'}}>{analysis.summary}</p></div>:<button className="sf-button" style={{marginTop:12,width:'100%'}} onClick={runAI}><Bot size={15}/>Analyze with AI</button>}</section></aside></div></div></div>
}
