import type { NextFunction, Request, Response } from 'express';
import { findUserById } from '../repositories/auth.repository.js';
import { createTicketSchema, ticketMessageSchema, ticketUpdateSchema } from '../schemas/ticket.schema.js';
import { addMessageToTicket, assignTicketToUser, createNewTicket, getTicketById, getTickets, updateExistingTicket } from '../services/ticket.service.js';
import { assignTicketSchema } from '../schemas/ticket-assignment.schema.js';

export async function getTicketsController(req: Request, res: Response, next: NextFunction) { try { const filters: { search?: string; status?: string; priority?: string } = {}; if (typeof req.query.search === 'string' && req.query.search) filters.search = req.query.search; if (typeof req.query.status === 'string' && req.query.status) filters.status = req.query.status; if (typeof req.query.priority === 'string' && req.query.priority) filters.priority = req.query.priority; res.json({ success: true, data: await getTickets(filters) }); } catch (error) { next(error); } }
export async function getTicketByIdController(req: Request, res: Response, next: NextFunction) { try { const ticket = await getTicketById(String(req.params.id)); if (!ticket) { res.status(404).json({ success: false, message: 'Ticket not found' }); return; } res.json({ success: true, data: ticket }); } catch (error) { next(error); } }
export async function createTicketController(req: Request, res: Response, next: NextFunction) { try { const parsed = createTicketSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ success: false, message: 'Invalid ticket data', errors: parsed.error.flatten() }); return; } res.status(201).json({ success: true, data: await createNewTicket(parsed.data) }); } catch (error) { next(error); } }
export async function updateTicketController(req: Request, res: Response, next: NextFunction) { try { const parsed = ticketUpdateSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ success: false, message: 'Invalid ticket update', errors: parsed.error.flatten() }); return; } res.json({ success: true, data: await updateExistingTicket(String(req.params.id), parsed.data) }); } catch (error) { next(error); } }
export async function addTicketMessageController(req: Request, res: Response, next: NextFunction) { try { const parsed = ticketMessageSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ success: false, message: 'Message is required', errors: parsed.error.flatten() }); return; } res.status(201).json({ success: true, data: await addMessageToTicket(String(req.params.id), parsed.data.content, req.user!.id) }); } catch (error) { next(error); } }
export async function assignTicketController(req: Request, res: Response, next: NextFunction) { try { const result = assignTicketSchema.safeParse(req.body); if (!result.success) { res.status(400).json({ success: false, message: 'Invalid assignment data', errors: result.error.flatten() }); return; } const user = await findUserById(result.data.assignedUserId); if (!user || user.status !== 'ACTIVE') { res.status(400).json({ success: false, message: 'Cannot assign ticket to an inactive or missing user' }); return; } res.json({ success: true, data: await assignTicketToUser(String(req.params.id), result.data.assignedUserId) }); } catch (error) { next(error); } }
